### PR TITLE
fix: support pydantic v2.x

### PR DESCRIPTION
**Pull request by CNSeniorious000**
- **Description:** As mentioned in #43, this package should be compatible with pydantic v2.x
- **Issue:** #43 
- **Dependencies:** pydantic <3 instead of pydantic <2
- **Tag maintainer:** @stonekim (I simply chose the first one in the list 😂)

### CODE REVIEW

**Comment by danielhjz** [comment]
HI! @CNSeniorious000 Thank you for contribution of your PR and helpful suggestion! We currently propose a [PR #42  ](https://github.com/baidubce/bce-qianfan-sdk/pull/42/files/b2c4299ced9772a54a1af8356673f6ce825f4806#r1377875080) about refactoring the config in `qianfan`. At the same time, in this PR dependency of pydantic will be upgraded to >=2. Would take a review if this could be an solution for your case in the Issue #44. ❤️

**Comment by CNSeniorious000** [comment]
Great. Using `pydantic-settings` for config management is elegant. I notice this line in #42:

```py
from langchain.pydantic_v1 import ......
```

and inside `langchain.pydantic_v1`:

```py
try:
    from pydantic.v1 import *  # noqa: F403
except ImportError:
    from pydantic import *  # noqa: F403


try:
    _PYDANTIC_MAJOR_VERSION: int = int(metadata.version("pydantic").split(".")[0])
except metadata.PackageNotFoundError:
    _PYDANTIC_MAJOR_VERSION = 0
```

This did what I did in #44. That's a good implemention. Looking forward to your next version. I'm still using `qianfan==0.0.7` just waiting for pydantic v2 support~ Thank you for your reply!

**Comment by danielhjz** [comment]
> Great. Using `pydantic-settings` for config management is elegant. I notice this line in #42:
> 
> ```python
> from langchain.pydantic_v1 import BaseModel, root_validator
> ```
> 
> and inside `langchain.pydantic_v1`:
> 
> ```python
> try:
>     from pydantic.v1 import *  # noqa: F403
> except ImportError:
>     from pydantic import *  # noqa: F403
> 
> 
> try:
>     _PYDANTIC_MAJOR_VERSION: int = int(metadata.version("pydantic").split(".")[0])
> except metadata.PackageNotFoundError:
>     _PYDANTIC_MAJOR_VERSION = 0
> ```
> 
> This did what I did in #44. That's a good implemention. Looking forward to your next version. I'm still using `qianfan==0.0.7` just waiting for pydantic v2 support~ Thank you for your reply!

Appreciate that. What's more, I wonder which features of `qianfan` are you mainly interested in currently. For example, llm features( chatCompletion or...), SFT training, agent or anything else?

**Comment by CNSeniorious000** [comment]
For me, currently I am not a heavy user of `qianfan`, I only use it for LLM inference. Maybe more in the future.
My main projects didn't use `langchain` so I encapsulate chains and agents myself, which only depends on `qianfan`'s ChatCompletion feature for now.

**Pull request closed without merging**
